### ISSUE TITLE
Handle launching tests on a remote queue with a personal access token

### ISSUE THREAD

**Issue by ayazhafiz** [rwx-research/abq#46]
#38 adds support for replaying previous ABQ test runs with a personal access token, without modifying a remote queue.

One unintentional implication of the present behavior is that a fresh run initialized with a personal access token will also not report test results to a remote queue. This is not the intended behavior.

We have a couple options:

1. Error out if you're creating a fresh run on a remote queue with a PAT
2. Fallback to reporting results to the remote queue if a fresh run uses a PAT

Maybe (1) is more preferable as it aligns with the use of PATs in ABQ to replay tests in CI, but maybe that is not the only use case we foresee.

**Comment by tonywok** [comment]
From standup @TAGraves:

if we have a PAT and no run ID, use an ephemeral queue
if we have a PAT and run ID that doesn't exist, error out

**Comment by ayazhafiz** [comment]
Addressed by https://github.com/rwx-research/abq/pull/52
